var app = angular.module('CERIGame', ['naif.base64'])
	.factory('socket', treatSocket)
	.service('accessDataService', accessDataService)
	.service('authService', authService)
	.service('sessionService', sessionService)
	.controller('authController', authController)
	.controller('profileController', profileController)
	.controller('routeController', routeController)
	.controller('quizzController', quizzController)
	.controller('leaderboardController', leaderboardController)
	.controller('notificationController', notificationController)
